# Local Development

version: '3.9'
services:

#  flask-server:
#    # default port 5000
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    container_name: api-flask-server
#    networks:
#      - vouch-proxy-demo-api
##    ports:
##      - "5000:5000"
#    restart: unless-stopped

  nginx:
    # default port 8443, 80
    image: nginx:1
    container_name: api-nginx
    networks:
      - vouch-proxy-demo-api
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    restart: unless-stopped

  vouch-proxy:
    # default port 9090
    container_name: api-vouch-proxy
    image: fabrictestbed/vouch-proxy:0.27.1
    networks:
      - vouch-proxy-demo-api
#    ports:
#      - "9090:9090"
    volumes:
      - ./vouch:/config
    restart: unless-stopped

networks:
  vouch-proxy-demo-api:
    name: vouch-proxy-demo-api
    driver: bridge