# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cilogon_tokens import CilogonTokens  # noqa: F401,E501
from swagger_server.models.status200_ok_single import Status200OkSingle  # noqa: F401,E501
from swagger_server import util


class ApiCilogonTokens(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, data: List[CilogonTokens]=None, size: int=1, status: int=200, type: str=None):  # noqa: E501
        """ApiCilogonTokens - a model defined in Swagger

        :param data: The data of this ApiCilogonTokens.  # noqa: E501
        :type data: List[CilogonTokens]
        :param size: The size of this ApiCilogonTokens.  # noqa: E501
        :type size: int
        :param status: The status of this ApiCilogonTokens.  # noqa: E501
        :type status: int
        :param type: The type of this ApiCilogonTokens.  # noqa: E501
        :type type: str
        """
        self.swagger_types = {
            'data': List[CilogonTokens],
            'size': int,
            'status': int,
            'type': str
        }

        self.attribute_map = {
            'data': 'data',
            'size': 'size',
            'status': 'status',
            'type': 'type'
        }
        self._data = data
        self._size = size
        self._status = status
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'ApiCilogonTokens':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The api_cilogon_tokens of this ApiCilogonTokens.  # noqa: E501
        :rtype: ApiCilogonTokens
        """
        return util.deserialize_model(dikt, cls)

    @property
    def data(self) -> List[CilogonTokens]:
        """Gets the data of this ApiCilogonTokens.


        :return: The data of this ApiCilogonTokens.
        :rtype: List[CilogonTokens]
        """
        return self._data

    @data.setter
    def data(self, data: List[CilogonTokens]):
        """Sets the data of this ApiCilogonTokens.


        :param data: The data of this ApiCilogonTokens.
        :type data: List[CilogonTokens]
        """

        self._data = data

    @property
    def size(self) -> int:
        """Gets the size of this ApiCilogonTokens.


        :return: The size of this ApiCilogonTokens.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this ApiCilogonTokens.


        :param size: The size of this ApiCilogonTokens.
        :type size: int
        """

        self._size = size

    @property
    def status(self) -> int:
        """Gets the status of this ApiCilogonTokens.


        :return: The status of this ApiCilogonTokens.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this ApiCilogonTokens.


        :param status: The status of this ApiCilogonTokens.
        :type status: int
        """

        self._status = status

    @property
    def type(self) -> str:
        """Gets the type of this ApiCilogonTokens.


        :return: The type of this ApiCilogonTokens.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ApiCilogonTokens.


        :param type: The type of this ApiCilogonTokens.
        :type type: str
        """

        self._type = type
