# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CilogonTokensIdentityToken(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, aud: str=None, auth_time: str=None, email: str=None, exp: str=None, family_name: str=None, given_name: str=None, iat: str=None, iss: str=None, jti: str=None, name: str=None, sub: str=None):  # noqa: E501
        """CilogonTokensIdentityToken - a model defined in Swagger

        :param aud: The aud of this CilogonTokensIdentityToken.  # noqa: E501
        :type aud: str
        :param auth_time: The auth_time of this CilogonTokensIdentityToken.  # noqa: E501
        :type auth_time: str
        :param email: The email of this CilogonTokensIdentityToken.  # noqa: E501
        :type email: str
        :param exp: The exp of this CilogonTokensIdentityToken.  # noqa: E501
        :type exp: str
        :param family_name: The family_name of this CilogonTokensIdentityToken.  # noqa: E501
        :type family_name: str
        :param given_name: The given_name of this CilogonTokensIdentityToken.  # noqa: E501
        :type given_name: str
        :param iat: The iat of this CilogonTokensIdentityToken.  # noqa: E501
        :type iat: str
        :param iss: The iss of this CilogonTokensIdentityToken.  # noqa: E501
        :type iss: str
        :param jti: The jti of this CilogonTokensIdentityToken.  # noqa: E501
        :type jti: str
        :param name: The name of this CilogonTokensIdentityToken.  # noqa: E501
        :type name: str
        :param sub: The sub of this CilogonTokensIdentityToken.  # noqa: E501
        :type sub: str
        """
        self.swagger_types = {
            'aud': str,
            'auth_time': str,
            'email': str,
            'exp': str,
            'family_name': str,
            'given_name': str,
            'iat': str,
            'iss': str,
            'jti': str,
            'name': str,
            'sub': str
        }

        self.attribute_map = {
            'aud': 'aud',
            'auth_time': 'auth_time',
            'email': 'email',
            'exp': 'exp',
            'family_name': 'family_name',
            'given_name': 'given_name',
            'iat': 'iat',
            'iss': 'iss',
            'jti': 'jti',
            'name': 'name',
            'sub': 'sub'
        }
        self._aud = aud
        self._auth_time = auth_time
        self._email = email
        self._exp = exp
        self._family_name = family_name
        self._given_name = given_name
        self._iat = iat
        self._iss = iss
        self._jti = jti
        self._name = name
        self._sub = sub

    @classmethod
    def from_dict(cls, dikt) -> 'CilogonTokensIdentityToken':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cilogon_tokens_identity_token of this CilogonTokensIdentityToken.  # noqa: E501
        :rtype: CilogonTokensIdentityToken
        """
        return util.deserialize_model(dikt, cls)

    @property
    def aud(self) -> str:
        """Gets the aud of this CilogonTokensIdentityToken.


        :return: The aud of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._aud

    @aud.setter
    def aud(self, aud: str):
        """Sets the aud of this CilogonTokensIdentityToken.


        :param aud: The aud of this CilogonTokensIdentityToken.
        :type aud: str
        """

        self._aud = aud

    @property
    def auth_time(self) -> str:
        """Gets the auth_time of this CilogonTokensIdentityToken.


        :return: The auth_time of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._auth_time

    @auth_time.setter
    def auth_time(self, auth_time: str):
        """Sets the auth_time of this CilogonTokensIdentityToken.


        :param auth_time: The auth_time of this CilogonTokensIdentityToken.
        :type auth_time: str
        """

        self._auth_time = auth_time

    @property
    def email(self) -> str:
        """Gets the email of this CilogonTokensIdentityToken.


        :return: The email of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this CilogonTokensIdentityToken.


        :param email: The email of this CilogonTokensIdentityToken.
        :type email: str
        """

        self._email = email

    @property
    def exp(self) -> str:
        """Gets the exp of this CilogonTokensIdentityToken.


        :return: The exp of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._exp

    @exp.setter
    def exp(self, exp: str):
        """Sets the exp of this CilogonTokensIdentityToken.


        :param exp: The exp of this CilogonTokensIdentityToken.
        :type exp: str
        """

        self._exp = exp

    @property
    def family_name(self) -> str:
        """Gets the family_name of this CilogonTokensIdentityToken.


        :return: The family_name of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._family_name

    @family_name.setter
    def family_name(self, family_name: str):
        """Sets the family_name of this CilogonTokensIdentityToken.


        :param family_name: The family_name of this CilogonTokensIdentityToken.
        :type family_name: str
        """

        self._family_name = family_name

    @property
    def given_name(self) -> str:
        """Gets the given_name of this CilogonTokensIdentityToken.


        :return: The given_name of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._given_name

    @given_name.setter
    def given_name(self, given_name: str):
        """Sets the given_name of this CilogonTokensIdentityToken.


        :param given_name: The given_name of this CilogonTokensIdentityToken.
        :type given_name: str
        """

        self._given_name = given_name

    @property
    def iat(self) -> str:
        """Gets the iat of this CilogonTokensIdentityToken.


        :return: The iat of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._iat

    @iat.setter
    def iat(self, iat: str):
        """Sets the iat of this CilogonTokensIdentityToken.


        :param iat: The iat of this CilogonTokensIdentityToken.
        :type iat: str
        """

        self._iat = iat

    @property
    def iss(self) -> str:
        """Gets the iss of this CilogonTokensIdentityToken.


        :return: The iss of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._iss

    @iss.setter
    def iss(self, iss: str):
        """Sets the iss of this CilogonTokensIdentityToken.


        :param iss: The iss of this CilogonTokensIdentityToken.
        :type iss: str
        """

        self._iss = iss

    @property
    def jti(self) -> str:
        """Gets the jti of this CilogonTokensIdentityToken.


        :return: The jti of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._jti

    @jti.setter
    def jti(self, jti: str):
        """Sets the jti of this CilogonTokensIdentityToken.


        :param jti: The jti of this CilogonTokensIdentityToken.
        :type jti: str
        """

        self._jti = jti

    @property
    def name(self) -> str:
        """Gets the name of this CilogonTokensIdentityToken.


        :return: The name of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this CilogonTokensIdentityToken.


        :param name: The name of this CilogonTokensIdentityToken.
        :type name: str
        """

        self._name = name

    @property
    def sub(self) -> str:
        """Gets the sub of this CilogonTokensIdentityToken.


        :return: The sub of this CilogonTokensIdentityToken.
        :rtype: str
        """
        return self._sub

    @sub.setter
    def sub(self, sub: str):
        """Sets the sub of this CilogonTokensIdentityToken.


        :param sub: The sub of this CilogonTokensIdentityToken.
        :type sub: str
        """

        self._sub = sub
