# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cilogon_tokens_identity_token import CilogonTokensIdentityToken  # noqa: F401,E501
from swagger_server import util


class CilogonTokens(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, access_token: str=None, identity_token: CilogonTokensIdentityToken=None, refresh_token: str=None):  # noqa: E501
        """CilogonTokens - a model defined in Swagger

        :param access_token: The access_token of this CilogonTokens.  # noqa: E501
        :type access_token: str
        :param identity_token: The identity_token of this CilogonTokens.  # noqa: E501
        :type identity_token: CilogonTokensIdentityToken
        :param refresh_token: The refresh_token of this CilogonTokens.  # noqa: E501
        :type refresh_token: str
        """
        self.swagger_types = {
            'access_token': str,
            'identity_token': CilogonTokensIdentityToken,
            'refresh_token': str
        }

        self.attribute_map = {
            'access_token': 'access_token',
            'identity_token': 'identity_token',
            'refresh_token': 'refresh_token'
        }
        self._access_token = access_token
        self._identity_token = identity_token
        self._refresh_token = refresh_token

    @classmethod
    def from_dict(cls, dikt) -> 'CilogonTokens':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The cilogon_tokens of this CilogonTokens.  # noqa: E501
        :rtype: CilogonTokens
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this CilogonTokens.


        :return: The access_token of this CilogonTokens.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this CilogonTokens.


        :param access_token: The access_token of this CilogonTokens.
        :type access_token: str
        """

        self._access_token = access_token

    @property
    def identity_token(self) -> CilogonTokensIdentityToken:
        """Gets the identity_token of this CilogonTokens.


        :return: The identity_token of this CilogonTokens.
        :rtype: CilogonTokensIdentityToken
        """
        return self._identity_token

    @identity_token.setter
    def identity_token(self, identity_token: CilogonTokensIdentityToken):
        """Sets the identity_token of this CilogonTokens.


        :param identity_token: The identity_token of this CilogonTokens.
        :type identity_token: CilogonTokensIdentityToken
        """

        self._identity_token = identity_token

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this CilogonTokens.


        :return: The refresh_token of this CilogonTokens.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this CilogonTokens.


        :param refresh_token: The refresh_token of this CilogonTokens.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token
