# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cilogon_tokens_identity_token import CilogonTokensIdentityToken  # noqa: F401,E501
from swagger_server.models.jwt_decoded_custom_claims import JwtDecodedCustomClaims  # noqa: F401,E501
from swagger_server import util


class JwtFullyDecoded(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, aud: str=None, cilogon_access_token: str=None, cilogon_identity_token: CilogonTokensIdentityToken=None, cilogon_refresh_token: str=None, custom_claims: JwtDecodedCustomClaims=None, exp: str=None, iss: str=None, username: str=None):  # noqa: E501
        """JwtFullyDecoded - a model defined in Swagger

        :param aud: The aud of this JwtFullyDecoded.  # noqa: E501
        :type aud: str
        :param cilogon_access_token: The cilogon_access_token of this JwtFullyDecoded.  # noqa: E501
        :type cilogon_access_token: str
        :param cilogon_identity_token: The cilogon_identity_token of this JwtFullyDecoded.  # noqa: E501
        :type cilogon_identity_token: CilogonTokensIdentityToken
        :param cilogon_refresh_token: The cilogon_refresh_token of this JwtFullyDecoded.  # noqa: E501
        :type cilogon_refresh_token: str
        :param custom_claims: The custom_claims of this JwtFullyDecoded.  # noqa: E501
        :type custom_claims: JwtDecodedCustomClaims
        :param exp: The exp of this JwtFullyDecoded.  # noqa: E501
        :type exp: str
        :param iss: The iss of this JwtFullyDecoded.  # noqa: E501
        :type iss: str
        :param username: The username of this JwtFullyDecoded.  # noqa: E501
        :type username: str
        """
        self.swagger_types = {
            'aud': str,
            'cilogon_access_token': str,
            'cilogon_identity_token': CilogonTokensIdentityToken,
            'cilogon_refresh_token': str,
            'custom_claims': JwtDecodedCustomClaims,
            'exp': str,
            'iss': str,
            'username': str
        }

        self.attribute_map = {
            'aud': 'aud',
            'cilogon_access_token': 'cilogon_access_token',
            'cilogon_identity_token': 'cilogon_identity_token',
            'cilogon_refresh_token': 'cilogon_refresh_token',
            'custom_claims': 'custom_claims',
            'exp': 'exp',
            'iss': 'iss',
            'username': 'username'
        }
        self._aud = aud
        self._cilogon_access_token = cilogon_access_token
        self._cilogon_identity_token = cilogon_identity_token
        self._cilogon_refresh_token = cilogon_refresh_token
        self._custom_claims = custom_claims
        self._exp = exp
        self._iss = iss
        self._username = username

    @classmethod
    def from_dict(cls, dikt) -> 'JwtFullyDecoded':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The jwt_fully_decoded of this JwtFullyDecoded.  # noqa: E501
        :rtype: JwtFullyDecoded
        """
        return util.deserialize_model(dikt, cls)

    @property
    def aud(self) -> str:
        """Gets the aud of this JwtFullyDecoded.


        :return: The aud of this JwtFullyDecoded.
        :rtype: str
        """
        return self._aud

    @aud.setter
    def aud(self, aud: str):
        """Sets the aud of this JwtFullyDecoded.


        :param aud: The aud of this JwtFullyDecoded.
        :type aud: str
        """

        self._aud = aud

    @property
    def cilogon_access_token(self) -> str:
        """Gets the cilogon_access_token of this JwtFullyDecoded.


        :return: The cilogon_access_token of this JwtFullyDecoded.
        :rtype: str
        """
        return self._cilogon_access_token

    @cilogon_access_token.setter
    def cilogon_access_token(self, cilogon_access_token: str):
        """Sets the cilogon_access_token of this JwtFullyDecoded.


        :param cilogon_access_token: The cilogon_access_token of this JwtFullyDecoded.
        :type cilogon_access_token: str
        """

        self._cilogon_access_token = cilogon_access_token

    @property
    def cilogon_identity_token(self) -> CilogonTokensIdentityToken:
        """Gets the cilogon_identity_token of this JwtFullyDecoded.


        :return: The cilogon_identity_token of this JwtFullyDecoded.
        :rtype: CilogonTokensIdentityToken
        """
        return self._cilogon_identity_token

    @cilogon_identity_token.setter
    def cilogon_identity_token(self, cilogon_identity_token: CilogonTokensIdentityToken):
        """Sets the cilogon_identity_token of this JwtFullyDecoded.


        :param cilogon_identity_token: The cilogon_identity_token of this JwtFullyDecoded.
        :type cilogon_identity_token: CilogonTokensIdentityToken
        """

        self._cilogon_identity_token = cilogon_identity_token

    @property
    def cilogon_refresh_token(self) -> str:
        """Gets the cilogon_refresh_token of this JwtFullyDecoded.


        :return: The cilogon_refresh_token of this JwtFullyDecoded.
        :rtype: str
        """
        return self._cilogon_refresh_token

    @cilogon_refresh_token.setter
    def cilogon_refresh_token(self, cilogon_refresh_token: str):
        """Sets the cilogon_refresh_token of this JwtFullyDecoded.


        :param cilogon_refresh_token: The cilogon_refresh_token of this JwtFullyDecoded.
        :type cilogon_refresh_token: str
        """

        self._cilogon_refresh_token = cilogon_refresh_token

    @property
    def custom_claims(self) -> JwtDecodedCustomClaims:
        """Gets the custom_claims of this JwtFullyDecoded.


        :return: The custom_claims of this JwtFullyDecoded.
        :rtype: JwtDecodedCustomClaims
        """
        return self._custom_claims

    @custom_claims.setter
    def custom_claims(self, custom_claims: JwtDecodedCustomClaims):
        """Sets the custom_claims of this JwtFullyDecoded.


        :param custom_claims: The custom_claims of this JwtFullyDecoded.
        :type custom_claims: JwtDecodedCustomClaims
        """

        self._custom_claims = custom_claims

    @property
    def exp(self) -> str:
        """Gets the exp of this JwtFullyDecoded.


        :return: The exp of this JwtFullyDecoded.
        :rtype: str
        """
        return self._exp

    @exp.setter
    def exp(self, exp: str):
        """Sets the exp of this JwtFullyDecoded.


        :param exp: The exp of this JwtFullyDecoded.
        :type exp: str
        """

        self._exp = exp

    @property
    def iss(self) -> str:
        """Gets the iss of this JwtFullyDecoded.


        :return: The iss of this JwtFullyDecoded.
        :rtype: str
        """
        return self._iss

    @iss.setter
    def iss(self, iss: str):
        """Sets the iss of this JwtFullyDecoded.


        :param iss: The iss of this JwtFullyDecoded.
        :type iss: str
        """

        self._iss = iss

    @property
    def username(self) -> str:
        """Gets the username of this JwtFullyDecoded.


        :return: The username of this JwtFullyDecoded.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username: str):
        """Sets the username of this JwtFullyDecoded.


        :param username: The username of this JwtFullyDecoded.
        :type username: str
        """

        self._username = username
