# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class JwtDecodedCustomClaims(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, aud: str=None, email: str=None, family_name: str=None, given_name: str=None, iss: str=None, name: str=None, sub: str=None):  # noqa: E501
        """JwtDecodedCustomClaims - a model defined in Swagger

        :param aud: The aud of this JwtDecodedCustomClaims.  # noqa: E501
        :type aud: str
        :param email: The email of this JwtDecodedCustomClaims.  # noqa: E501
        :type email: str
        :param family_name: The family_name of this JwtDecodedCustomClaims.  # noqa: E501
        :type family_name: str
        :param given_name: The given_name of this JwtDecodedCustomClaims.  # noqa: E501
        :type given_name: str
        :param iss: The iss of this JwtDecodedCustomClaims.  # noqa: E501
        :type iss: str
        :param name: The name of this JwtDecodedCustomClaims.  # noqa: E501
        :type name: str
        :param sub: The sub of this JwtDecodedCustomClaims.  # noqa: E501
        :type sub: str
        """
        self.swagger_types = {
            'aud': str,
            'email': str,
            'family_name': str,
            'given_name': str,
            'iss': str,
            'name': str,
            'sub': str
        }

        self.attribute_map = {
            'aud': 'aud',
            'email': 'email',
            'family_name': 'family_name',
            'given_name': 'given_name',
            'iss': 'iss',
            'name': 'name',
            'sub': 'sub'
        }
        self._aud = aud
        self._email = email
        self._family_name = family_name
        self._given_name = given_name
        self._iss = iss
        self._name = name
        self._sub = sub

    @classmethod
    def from_dict(cls, dikt) -> 'JwtDecodedCustomClaims':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The jwt_decoded_CustomClaims of this JwtDecodedCustomClaims.  # noqa: E501
        :rtype: JwtDecodedCustomClaims
        """
        return util.deserialize_model(dikt, cls)

    @property
    def aud(self) -> str:
        """Gets the aud of this JwtDecodedCustomClaims.


        :return: The aud of this JwtDecodedCustomClaims.
        :rtype: str
        """
        return self._aud

    @aud.setter
    def aud(self, aud: str):
        """Sets the aud of this JwtDecodedCustomClaims.


        :param aud: The aud of this JwtDecodedCustomClaims.
        :type aud: str
        """

        self._aud = aud

    @property
    def email(self) -> str:
        """Gets the email of this JwtDecodedCustomClaims.


        :return: The email of this JwtDecodedCustomClaims.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this JwtDecodedCustomClaims.


        :param email: The email of this JwtDecodedCustomClaims.
        :type email: str
        """

        self._email = email

    @property
    def family_name(self) -> str:
        """Gets the family_name of this JwtDecodedCustomClaims.


        :return: The family_name of this JwtDecodedCustomClaims.
        :rtype: str
        """
        return self._family_name

    @family_name.setter
    def family_name(self, family_name: str):
        """Sets the family_name of this JwtDecodedCustomClaims.


        :param family_name: The family_name of this JwtDecodedCustomClaims.
        :type family_name: str
        """

        self._family_name = family_name

    @property
    def given_name(self) -> str:
        """Gets the given_name of this JwtDecodedCustomClaims.


        :return: The given_name of this JwtDecodedCustomClaims.
        :rtype: str
        """
        return self._given_name

    @given_name.setter
    def given_name(self, given_name: str):
        """Sets the given_name of this JwtDecodedCustomClaims.


        :param given_name: The given_name of this JwtDecodedCustomClaims.
        :type given_name: str
        """

        self._given_name = given_name

    @property
    def iss(self) -> str:
        """Gets the iss of this JwtDecodedCustomClaims.


        :return: The iss of this JwtDecodedCustomClaims.
        :rtype: str
        """
        return self._iss

    @iss.setter
    def iss(self, iss: str):
        """Sets the iss of this JwtDecodedCustomClaims.


        :param iss: The iss of this JwtDecodedCustomClaims.
        :type iss: str
        """

        self._iss = iss

    @property
    def name(self) -> str:
        """Gets the name of this JwtDecodedCustomClaims.


        :return: The name of this JwtDecodedCustomClaims.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this JwtDecodedCustomClaims.


        :param name: The name of this JwtDecodedCustomClaims.
        :type name: str
        """

        self._name = name

    @property
    def sub(self) -> str:
        """Gets the sub of this JwtDecodedCustomClaims.


        :return: The sub of this JwtDecodedCustomClaims.
        :rtype: str
        """
        return self._sub

    @sub.setter
    def sub(self, sub: str):
        """Sets the sub of this JwtDecodedCustomClaims.


        :param sub: The sub of this JwtDecodedCustomClaims.
        :type sub: str
        """

        self._sub = sub
